.PHONY: test checks build

test:
	go test -v ./...
checks:
	go fmt ./...
	go vet ./...
	staticcheck ./...
build:
	go build -ldflags='-w -s -X github.com/redwebcreation/nest/globals.Version=testing' -gcflags=all='-l'