.PHONY: test checks build

tests: test
test:
	go test -v ./...
checks:
	gosec ./...
	go fmt ./...
	go vet ./...
	golangci-lint run	 ./...
build:
	go build -ldflags='-w -s -X github.com/redwebcreation/nest/globals.Version=testing' -gcflags=all='-l'