name: Tests

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.18-beta2
      - name: Run tests
        run: go test -v ./...
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.18-beta2
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.18-beta2
      - name: Install dev tools
        run: make install
      - name: Run static analysis
        run: make lint


